[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 200

[[redirects]]  
  from = "/upload"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/profile"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/auth"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/user/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/robots.txt/*"
  to = "/robots.txt"
  status = 200

